export type ContactFormData = {
  name: string;
  email: string;
  purpose: string;
  description: string;
};

export const smokeContactFormData: ContactFormData = {
  name: 'QA Smoke Tester',
  email: 'qa.smoke.tester@example.com',
  purpose: 'Custom AI Solutions Factory',
  description: 'Smoke test message generated by automated QA. Please ignore.',
};
